### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-developer-docs#40]

**Comment by philoserf** [comment]
Currently documented at <https://github.com/obsidianmd/obsidian-developer-docs/blob/main/en/Home.md#contributing>

**Comment by sigrunixia** [comment]
We should probably expand it more on the readme itself. 

The contributing portion on the standard [help documents](https://github.com/obsidianmd/obsidian-help#contribute) are a good template, but we may want to add another step about finalizing changes before it gets to PR stage. 

## Proposed update
---

## Contributing

**You can contribute in several ways**:

- **Fix typos and mistakes**: If you want to fix a typo or other small modifications, you can submit a pull request without creating an issue. For smaller edits, you can use the GitHub web interface instead of cloning the repository.
- **Add missing, outdated, or clarifying  content**: If you want to add, remove, or expand on current content, please [submit an issue](https://github.com/obsidianmd/obsidian-developer-docs/issues/new) before you start working on it.
- Any contributions to the docs must follow our [Style guide](https://help.obsidian.md/Contributing+to+Obsidian/Style+guide).

**To make changes to Obsidian Developer docs**:

- Fork the [obsidian-developer-docs](https://github.com/obsidianmd/obsidian-developer-docs) repository
- In the Obsidian vault switcher, select Open folder as vault
- Make your change in Obsidian
- Confirm the change is presentable in **Reading View**
- Commit your change to your fork
- Submit your PR to the obsidian-developer-docs repo for final review

**Comment by sigrunixia** [comment]
When you have a moment of time, can I have your perspective on if anything else should be included, since this is about more technical detailings than the help-docs, @liamcain ?

**Comment by sigrunixia** [comment]
Proposed change in https://docs.obsidian.md/Home#Contributing

**Before**:
```md
If you see any errors or room for improvement on this site, feel free to open an issue or pull request on [our GitHub repository](https://github.com/obsidianmd/obsidian-developer-docs). Thank you in advance for contributing!
```

**After**
```md
If you see any errors or room for improvement on this site, or want to submit a PR, feel free to open an issue on [our GitHub repository](https://github.com/obsidianmd/obsidian-developer-docs). Additional details are available on our [Readme](https://github.com/obsidianmd/obsidian-developer-docs#readme).

Thank you in advance for contributing!
```
